[project]
name = "cylclingpredict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "procyclingstats>=0.2.8",
    "requests>=2.31.0",
    "scikit-learn>=1.8.0",
    "torch>=2.11.0",
]
